### PR TITLE
Fix parsing of latest version of classic Google search

### LINKED ISSUE #105: Dom change - possible fix suggestion & examples attached.
Hey, 

I'm getting a Classical Result DOM error every 10 to 30 requests.  

I've attached : 

[BadDom.zip](https://github.com/serp-spider/search-engine-google/files/2214419/BadDom.zip) is a ZIP of 4 example DOM files 
[Bridal Accessories Bakewell7560.html.zip](https://github.com/serp-spider/search-engine-google/files/2214524/Bridal.Accessories.Bakewell7560.html.zip) is a ZIP of 1 rendered HTML file

Here's a script to parse any of the BadDom files: 

```php


require_once __DIR__ . '/vendor/autoload.php';

use Serps\SearchEngine\Google\GoogleUrl;
use Serps\SearchEngine\Google\Page\GoogleSerp;

$url = GoogleUrl::fromString('https://google.com/?q=your+keywords');

$fileContent = file_get_contents(__DIR__ .  '/BadDom/A4 Landscape Dorchester890.html');

// Create a serp with the file content and the url
$serp = new GoogleSerp($fileContent, $url);

// and analyse it
$naturalResults = $serp->getNaturalResults();

prinr_r($naturalResults ) ;


```

Here's an example of a classical result element from the rendered HTML page: 
```html 
<div class="g"><!--m-->
    <div data-hveid="90" data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQFQhaKAAwAg">
        <div class="rc">
            <div class="r"><a href="http://www.bridesofbakewell.com/" ping="/url?sa=t&amp;source=web&amp;rct=j&amp;url=http://www.bridesofbakewell.com/&amp;ved=0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQFghbMAI"><h3
                    class="LC20lb">Brides of Bakewell: Home</h3><br>
                <div style="display:inline-block" class="TbwUpd"><cite class="iUh30">www.bridesofbakewell.com/</cite></div>
            </a><span><div class="action-menu ab_ctl"><a class="GHDvEf ab_button" href="#" id="am-b2" aria-label="Result options" aria-expanded="false" aria-haspopup="true" role="button"
                                                         jsaction="m.tdd;keydown:m.hbke;keypress:m.mskpe" data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQ7B0IXDAC"><span class="mn-dwn-arw"></span></a><div
                    class="action-menu-panel ab_dropdown" role="menu" tabindex="-1" jsaction="keydown:m.hdke;mouseover:m.hdhne;mouseout:m.hdhue" data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQqR8IXTAC"><ol><li
                    class="action-menu-item ab_dropdownitem" role="menuitem"><a class="fl"
                                                                                href="http://webcache.googleusercontent.com/search?q=cache:NcvOB9MEhX0J:www.bridesofbakewell.com/+&amp;cd=3&amp;hl=en&amp;ct=clnk&amp;gl=jp"
                                                                                ping="/url?sa=t&amp;source=web&amp;rct=j&amp;url=http://webcache.googleusercontent.com/search%3Fq%3Dcache:NcvOB9MEhX0J:www.bridesofbakewell.com/%2B%26cd%3D3%26hl%3Den%26ct%3Dclnk%26gl%3Djp&amp;ved=0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQIAheMAI">Cached</a></li><li
                    class="action-menu-item ab_dropdownitem" role="menuitem"><a class="fl"
                                                                                href="/search?near=middlesbrough,UK&amp;pws=0&amp;q=related:www.bridesofbakewell.com/+Bridal+Accessories+Bakewell&amp;tbo=1&amp;sa=X&amp;ved=0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQHwhfMAI">Similar</a></li></ol></div></div></span>
            </div>
            <div class="s">
                <div><span
                        class="st">Welcome to <em>Brides</em> of <em>Bakewell</em> – a beautiful <em>wedding</em> boutique in the Derbyshire ... <em>accessories</em> when you also buy a <em>wedding</em> dress from <em>Brides</em> of <em>Bakewell</em>.</span>
                </div>
            </div>
            <div jsl="$t t--ddbPTeIsNI;$x 0;" class="r-iMXdFOFX_Ubc" data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQ2Z0BCGAwAg">
                <div class="AUiS2 iMXdFOFX_Ubc-7_jVsFT_9Io" id="eobm_2" data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQx40DCGEwAg">
                    <div id="eobd_2" class="iMXdFOFX_Ubc-uhagcrfPmuU" style="display:none">
                        <div data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQsKwBCGIoADAC">alexandra bridal</div>
                        <div data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQsKwBCGMoATAC">stella york 6245</div>
                        <div data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQsKwBCGQoAjAC">bridesmaid dresses</div>
                        <div data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQsKwBCGUoAzAC">wedding dresses</div>
                        <div data-ved="0ahUKEwiWt6KQgq7cAhWKXrwKHQjyCaUQsKwBCGYoBDAC">asos</div>
                    </div>
                    <span class="XCKyNd" id="eobs_2" aria-label="Dismiss suggested follow ups" role="button" tabindex="0" jsaction="r.pz0qjfJrMDo" data-rtid="iMXdFOFX_Ubc" jsl="$x 2;"></span>
                    <div>
                        <div class="d8lLoc iMXdFOFX_Ubc-eEjGhTK0s34" id="eobc_2"><h4 class="eJ7tvc iMXdFOFX_Ubc-ZgH0LU9o8RU" id="eobp_2">People also search for</h4>
                            <div class="hYkSRb iMXdFOFX_Ubc-ICxnu-SGsqE" id="eobr_2"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--n--></div>

```

Seems like the error is that h3 class is not always `r`. 

Your library is better than anything I've ever produced, but my observation would be that in the `ClassicalResult->parseNode()`  maybe the old code of `->xpathQuery("descendant::h3[@class='r'][1]/a", $node)` is too specific now that a class of LC20lb is sometimes returned on the h3 element - should it be replaced with a more generic: `->xpathQuery("descendant::h3", $node)` ? 

I've tested the following and it seems to work in `ClassicalResult->parseNode()` to return the title : 

```php

        // find the title/url
        /* @var $aTag \DOMElement */
        $aTag=$dom
//             ->xpathQuery("descendant::h3[@class='r'][1]/a", $node) // old
            ->xpathQuery("descendant::h3", $node) // new
            ->item(0);
        if (!$aTag) {
            throw new InvalidDOMException('Cannot parse a classical result.');
        }
```

If you're happy with it I'll do a pull request with the amendment ?

### LINKED ISSUE #110: DOM Change (Cannot parse a classical result.)
> Cannot parse a classical result. Google DOM has possibly changed and an update may be required.

[mobile-device-management.html.zip](https://github.com/serp-spider/search-engine-google/files/2386168/65b6be0a-7619-4018-97c9-989cdec53319.html.zip)

### PR DESCRIPTION
**Pull request by msiemens**
This fixes parsing the latest version of classic Google search results.

Closes #105
Closes #110

### CODE REVIEW

**Comment by msiemens** [comment]
Still got a test error, I'm currently looking into it

**Comment by msiemens** [comment]
Fixed, all tests pass now!

**Comment by dennisoderwald** [comment]
@gsouf Can you please merge that?

File: src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php [hunk 1]
```diff
@@ -32,23 +32,35 @@ protected function parseNode(GoogleDom $dom, \DomElement $node)
...
+        /* @var $h3Tag \DOMElement */
+        $h3Tag = $dom
+            ->xpathQuery('descendant::h3', $node)
+            ->item(0);
+        if (!$h3Tag) {
+            throw new InvalidDOMException('Cannot parse a classical result.');
+        }
+
         $destinationTag = $dom
-            ->cssQuery('div.f cite', $node)
```
Comment (gsouf) [inline src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php]: Can you please keep the css query here instead of the xpath, it's easier to read. You can have multiple css rules by using a coma ``->cssQuery(".rule1, .rule2")``.

File: src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php [hunk 2]
```diff
@@ -32,23 +32,35 @@ protected function parseNode(GoogleDom $dom, \DomElement $node)
...
+            ->xpathQuery("descendant::div[starts-with(@class, 'f ') or @class='TbwUpd']//cite", $node)
             ->getNodeAt(0);
 
+        if (is_a($destinationTag, 'Serps\Core\Dom\NullDomNode')) {
```
Comment (gsouf) [inline src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php]: Can you please use a class reference instead of a string

``Serps\Core\Dom\NullDomNode::class`` instead of ``"Serps\Core\Dom\NullDomNode"``

File: src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php (hunk 1 above)
Comment (msiemens) [reply src/Parser/Evaluated/Rule/Natural/Classical/ClassicalResult.php]: Ah, didn't know that it works here. I'll update it in a minute

**Comment by gsouf** [comment]
Hi @msiemens 

Thanks for your contribution, that's appreciated. 

I added 2 comments that are quick fixes you can make to the PR. Can you look at them please?

**Comment by msiemens** [comment]
Thanks! I've changed the code as requested 🙃

**Comment by msiemens** [comment]
Thanks for the quick merge, @gsouf ❤️

**Comment by gsouf** [comment]
You're welcome, thanks to you for the good PR with updated unit tests.

That's published with version ``v0.4.3``
